### ISSUE TITLE
Issue when importing modules

### ISSUE THREAD

**Issue by cici7941** [linkedin/luminol#6]
Hello,

When I try to import the modules, I got some error messages here,
```>>> from luminol.correlator import Correlator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/luminol/correlator.py", line 19, in <module>
    from luminol.anomaly_detector import AnomalyDetector
  File "/usr/local/lib/python3.4/dist-packages/luminol/anomaly_detector.py", line 19, in <module>
    from luminol.algorithms.anomaly_detector_algorithms.all import anomaly_detector_algorithms
  File "/usr/local/lib/python3.4/dist-packages/luminol/algorithms/anomaly_detector_algorithms/all.py", line 12, in <module>
    from luminol.algorithms.anomaly_detector_algorithms import *
  File "/usr/local/lib/python3.4/dist-packages/luminol/algorithms/anomaly_detector_algorithms/default_detector.py", line 12, in <module>
    from exp_avg_detector import ExpAvgDetector
ImportError: No module named 'exp_avg_detector'```

I think there is some issue with the module `exp_avg_detector`.

Could you please help fix that?

Thanks a lot!

Sophie

**Comment by taintedkernel** [comment]
Hi Sophie, could you provide some more context on your issue?
Specifically, what versions of the library and Python are you using?

I ran a quick test on my end - created a new virtualenv, installed luminol
via pip and imported the correlator module without issue.  Using a somewhat
older Python 2.7.6 on my end.

Anthony

**Comment by cici7941** [comment]
Hi Anthony,

Thanks for your response. I just installed the luminol library today. So I believe it's the latest version. And for Python, I am running 3.4.3.

Best,
Sophie

**Comment by cici7941** [comment]
just run it on Python 2.7.11  no error messages. Hope it can work on Python 3.4 as well

**Comment by taintedkernel** [comment]
That could be the problem, I don't believe it's been fully tested on 3.4
quite yet.  If I find anything out regarding compatibility I will let you
know.

**Comment by brennv** [comment]
Work in-progress PR #13 started to add Python 3

Tests passing for Python 2.7 and 3.6
61% coverage

**Comment by brennv** [comment]
Python 3 support added with #28 ... pypi release still pending you can:
```
pip install git+https://github.com/linkedin/luminol.git
```
